#!/usr/bin/env bash
# Script to create PID file and handles SIGTERM, SIGINT, SIGQUIT
echo "$$" > /tmp/myscript.pid

stty -echoctl

trap "echo 'I hate the kill command'; rm /tmp/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm /tmp/myscript.pid; exit" SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
